In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("movie_metadata.csv")

In [8]:
movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [14]:
movies["director_name"].unique()

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Scott Smith', 'Benjamin Roberds', 'Daniel Hsia'], dtype=object)

In [17]:
movies[movies['director_name'] == 'James Cameron']

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
288,Color,James Cameron,210.0,153.0,0.0,539.0,Jenette Goldstein,780.0,204843350.0,Action|Sci-Fi,...,983.0,English,USA,R,102000000.0,1991.0,604.0,8.5,2.35,13000
291,Color,James Cameron,94.0,141.0,0.0,618.0,Tia Carrere,2000.0,146282411.0,Action|Comedy|Thriller,...,351.0,English,USA,R,115000000.0,1994.0,1000.0,7.2,2.35,0
606,Color,James Cameron,82.0,171.0,0.0,638.0,Todd Graff,2000.0,54222000.0,Adventure|Drama|Sci-Fi|Thriller,...,380.0,English,USA,PG-13,69500000.0,1989.0,650.0,7.6,2.35,0
2486,Color,James Cameron,250.0,154.0,0.0,604.0,Carrie Henn,2000.0,85200000.0,Action|Adventure|Sci-Fi,...,1076.0,English,USA,R,18500000.0,1986.0,626.0,8.4,1.85,18000
3575,Color,James Cameron,204.0,107.0,0.0,255.0,Brian Thompson,2000.0,38400000.0,Action|Sci-Fi,...,692.0,English,UK,R,6500000.0,1984.0,663.0,8.1,1.85,13000

In [21]:
movies2 = movies[['director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name', 'movie_title', 'imdb_score', 'title_year']]

In [27]:
movies2[(movies2['title_year']<2000) & (movies2['title_year']>1990)]

,director_name,actor_1_name,actor_2_name,actor_3_name,movie_title,imdb_score,title_year
26,James Cameron,Leonardo DiCaprio,Kate Winslet,Gloria Stuart,Titanic,7.7,1997.0
71,Barry Sonnenfeld,Will Smith,Salma Hayek,Bai Ling,Wild Wild West,4.8,1999.0
76,Kevin Reynolds,Jeanne Tripplehorn,Rick Aviles,Zakes Mokae,Waterworld,6.1,1995.0
151,Michael Bay,Bruce Willis,Steve Buscemi,Will Patton,Armageddon,6.6,1998.0
166,Richard Donner,Jet Li,Rene Russo,Darlene Love,Lethal Weapon 4,6.6,1998.0
...,...,...,...,...,...,...,...
5011,Neil LaBute,Stacy Edwards,Matt Malloy,Jason Dixie,In the Company of Men,7.3,1997.0
5015,Richard Linklater,Tommy Pallotta,Richard Linklater,Jean Caffeine,Slacker,7.1,1991.0
5029,Kiyoshi Kurosawa,KÃ´ji Yakusho,Anna Nakagawa,Denden,The Cure,7.4,1997.0
5032,Ash Baron-Cohen,Peter Greene,Stanley B. Herman,James Noble,Bang,6.4,1995.0
5035,Robert Rodriguez,Carlos Gallardo,Peter Marquardt,Consuelo GÃ³mez,El Mariachi,6.9,1992.0

In [33]:
movies_1990 = movies2[movies2['title_year']<1990]

In [35]:
movies_1990.to_csv("movies_1990.csv")